### PR TITLE
Added `dotenv` for environment variables to be readable

### PR DESCRIPTION
**Pull request by myckhel**

### CODE REVIEW

**Comment by amitavroy** [comment]
Why do you need to directly load the .env through that package? We already have the Nest service which does that, right?

**Comment by myckhel** [comment]
When you run the migration through cli, no env is loaded because its not nest service calling it.
This change will make the codes work with typeorm v0.3+

**Comment by amitavroy** [comment]
That's why I have this file: https://github.com/amitavdevzone/nest-js-quiz-manager/blob/master/server/src/config/typeorm.config-migrations.ts. 

Loading the dotenv to use env variables outside nest feels a little strange. So, I am closing this PR.

**Comment by myckhel** [comment]
@amitavroy maybe you have not tried this peoject with typeorm v0.3+ to see the issue.
See comments section for issues https://youtu.be/1-MRmLsUrAo

**Comment by amitavroy** [comment]
Yes, I know the current setup doesn't work with TypeORM 0.3x. 

The new version of TypeORM has made some changes that needs DataSource and I am not able to get that to work with the current setup. However, this approach seems wrong because if we are using the .env values directly i.e. without the framework suggested way, then it's a problem. 

I am still looking for a correct implementation and will update the codebase once I am able to find it. 

Thanks for the effort my friend.

**Pull request closed without merging**
